### ISSUE TITLE
`main.exe` fails checksum after compilation

### ISSUE THREAD

**Issue by tsunamistate** [Xeeynamo/sotn-decomp#1075]
OS: Ubuntu 22.04.3 via WSL2

```
sha1sum --check config/check.us.sha
build/us/main.exe: FAILED
...
sha1sum: WARNING: 1 computed checksum did NOT match
make: *** [Makefile:146: check] Error 1
```

Bisected to 437856d54526bd28a2b4d4f1b766ebfcd13ee0e3

**Comment by sozud** [comment]
Is tools/maspsx on commit [d19cddd](https://github.com/mkst/maspsx/tree/d19cddd9ed40e389e1e7c35e46fd5a768504a66f) ?

**Comment by tsunamistate** [comment]
Whelp, after updating submodules (I assumed `git pull` did it, it doesn't) and recompiling, checksum is OK
Sorry for the trouble 🥺
