### ISSUE TITLE
Add stage overlay NO0

### ISSUE THREAD

**Issue by Xeeynamo** [Xeeynamo/sotn-decomp#1636]
Refer to the guide on [how to add new overlays](https://github.com/Xeeynamo/sotn-decomp/wiki/Decompilation#add-new-overlay).

This is the next stage connected to Alchemy Lab (NZ0), which is already present in our decomp. It seems to be the default stage used by the developers. Might this be the very first one they developed?

**Comment by bismurphy** [comment]
Correct! Working on this as well as tools for streamlining future overlay creation. Should be submitting this overlay within 1 week hopefully.

**Comment by mrmidi** [comment]
I'm pretty sure that it's done
