### ISSUE TITLE
SEL func_801BAB70

### ISSUE THREAD

**Issue by Xeeynamo** [Xeeynamo/sotn-decomp#719]
## What

[func_801BAB70](https://raw.githubusercontent.com/Xeeynamo/sotn-decomp/gh-duplicates/function_calls/sel.func_801BAB70.svg) is a small function that has not yet been decompiled. It belongs to the stage `SEL`.

This is a good function for those who wants to start contributing to the project and have little programming skills. Please follow [Build](https://github.com/Xeeynamo/sotn-decomp/wiki/Build) and [Decompilation](https://github.com/Xeeynamo/sotn-decomp/wiki/Decompilation) to know how to start with decompiling functions.

## Acceptance criteria

The function `func_801BAB70` must all be written in C, running `make all` must return `OK` and a Pull Request must follow. The issue will be marked as Complete if the Pull Request will be accepted and merged.

**Comment by joshlory** [comment]
There are a few different target assemblies of this function on decomp.me, which is the correct starting point?

**Comment by sozud** [comment]
We believe it's handwritten asm so this ticket is actually misleading now https://github.com/Xeeynamo/sotn-decomp/commit/23a143b29526aa8c4b88546c7ca8bf91567eab9b

**Comment by Xeeynamo** [comment]
I am going to close this then --asm-dir-prefix asm/pspeu
